{% set name = "sphinx-jsonschema" %}
{% set version = "1.17.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sphinx-jsonschema-{{ version }}.tar.gz
  sha256: 90880aac56382a52d1ea928ec21fcd315ca732469d04813d5095de9eb6cdd832

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - docutils
    - jsonpointer
    - pyyaml
    - requests
    - sphinx

test:
  commands:
    - pip check
    # I need to use importlib due to the - character in the package name.
    - python -c "import importlib; importlib.import_module('sphinx-jsonschema')"
  requires:
    - pip
  # There are currently no functional unit tests ( https://github.com/lnoor/sphinx-jsonschema/issues/56 ).

about:
  home: https://github.com/lnoor/sphinx-jsonschema
  summary: Sphinx extension to display JSON Schema
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maresb
